//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cicekci.DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Siparis
    {
        public int Id { get; set; }
        [MaxLength(50), Required]
        public string MusteriAdi { get; set; }
        public System.DateTime SiparisTarihi { get; set; }
        [MaxLength(16), Required]
        public string KartNo { get; set; }
        public int UrunId { get; set; }
        public int Miktar { get; set; }
        public Nullable<int> UyeId { get; set; }
    
        public virtual Urun Urun { get; set; }
        public virtual Uye Uye { get; set; }
    }
}
